#clang++ -o test_dct chenidct.cpp test_dct.cpp -I/usr/local/packages/Xilinx/Vivado_HLS/2014.2/include
#./test_dct
#clang++ -o test_color colorconvert.cpp test_colorconvert.cpp -I/usr/local/packages/Xilinx/Vivado_HLS/2014.2/include
#./test_color
all: 
	g++ -std=c++11 -o output main.cpp loadjpg.cpp comparebmp.cpp savejpg.cpp  modules_isolated.cpp book_keeping.cpp -w 

