#!/bin/bash


start=`date +%s`
#removing all the previous files
rm ref_results_pickled
rm pareto_set_file.txt
rm ref.png
rm combine.png
rm pickled_results_pareto
rm pareto_curved_combined_pickled
echo "done with the stage 0, removing all the files"

cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/disparity/src/c/
cp computeSAD_apx.txt computeSAD.c
cp finalSAD_apx.txt finalSAD.c
cp integralImage2D2D_apx.txt integralImage2D2D.c

cd /home/polaris/behzad/behzad_local/apx_tool_chain/src/python_files/
python run_tool_chain.py
cp pickled_results_pareto ref_results_pickled
cp pickled_results_all_points ref_results_pickled_all_points
rm pareto_set_file.txt
cp ../../generated_text/finalResult.png ref.png
echo "done with the stage 1: flattening and apx of all files"



#
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/bencmhmarks/disparity/src/c/
cp computeSAD_acc.txt computeSAD.c
cp finalSAD_acc.txt finalSAD.c
cp integralImage2D2D_acc.txt integralImage2D2D.c

cp computeSAD_apx.txt computeSAD.c
cp integralImage2D2D_apx.txt integralImage2D2D.c 

cd /home/polaris/behzad/behzad_local/apx_tool_chain/src/python_files/
python run_tool_chain.py

rm ../../generated_text/finalResult.png 
rm pickled_results_pareto
cp pickled_results_all_points results_pickled_all_points_s2
echo "done with the stage 2: apx of some files"



cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/disparity/src/c/
cp computeSAD_acc.txt computeSAD.c
cp finalSAD_acc.txt finalSAD.c
cp integralImage2D2D_acc.txt integralImage2D2D.c


cp finalSAD_apx.txt finalSAD.c

cd /home/polaris/behzad/behzad_local/apx_tool_chain/src/python_files/
python run_tool_chain.py
rm ../../generated_text/finalResult.png 
rm pickled_results_pareto
cp pickled_results_all_points results_pickled_all_points_s3
echo "done with the stage 3: apx of some files"
#
#returning all the files to approximate version (so we can get the accurate result)
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/disparity/src/c/
cp computeSAD_apx.txt computeSAD.c
cp finalSAD_apx.txt finalSAD.c
cp integralImage2D2D_apx.txt integralImage2D2D.c


cd /home/polaris/behzad/behzad_local/apx_tool_chain/src/python_files/
python combine_paretos.py
python compare_pareto_curves.py >> compare_results.txt
cp ../../generated_text/finalResult.png combine.png
echo "done with stage 4:combining the paretos and comparing"

end=`date +%s`
runtime=$((end-start))
echo total running time of the script was: $runtime
