#!/bin/bash

#removing all the previous files
rm pareto_of_flattened
rm pareto_set_file.txt
rm ref.png
rm combine.png
rm pickled_results
rm pareto_of_combined
echo "done0"

cd ../CSrc/
cp mat_mul_unfolded_algo0_apx.txt mat_mul_unfolded_algo0.cpp
cp mat_mul_unfolded_algo1_apx.txt mat_mul_unfolded_algo1.cpp
cd ../python_files/
python run_tool_chain.py
cp pickled_results pareto_of_flattened

rm pareto_set_file.txt
cp ../../generated_text/finalResult.png ref.png
echo "done1"

cd ../CSrc
cp mat_mul_unfolded_algo0_accurate.txt mat_mul_unfolded_algo0.cpp
cp mat_mul_unfolded_algo1_apx.txt mat_mul_unfolded_algo1.cpp
cd ../python_files/
python run_tool_chain.py
rm ../../generated_text/finalResult.png 
rm pickled_results
echo "done2"

cd ../CSrc
cp mat_mul_unfolded_algo0_apx.txt mat_mul_unfolded_algo0.cpp
cp mat_mul_unfolded_algo1_accurate.txt mat_mul_unfolded_algo1.cpp
cd ../python_files/
python run_tool_chain.py
rm ../../generated_text/finalResult.png 
rm pickled_results
echo "done3"

python combine_paretos.py
python compare_pareto_curves.py >> compare_results.txt
cp ../../generated_text/finalResult.png combine.png
echo "done4"

