#!/bin/bash

start=`date +%s`
#removing all the previous files
#rm pareto_of_flattened
#rm pareto_set_file.txt
#rm ref.png
#rm combine.png
#rm pickled_results_pareto
#rm pareto_of_combined
#echo "done with the stage 0, removing all the files"
#
#cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/sift/src/c/
#cp imsmooth_apx.txt imsmooth.c
#cp diffss_apx.txt diffss.c
#
#cd /home/polaris/behzad/behzad_local/apx_tool_chain/src/python_files/
#python run_tool_chain.py
#cp pickled_results_pareto pareto_of_flattened
#cp pickled_results_all_points all_of_flattned

#
#rm pareto_set_file.txt
#cp ../../generated_text/finalResult.png ref.png
#echo "done with the stage 1: flattening and apx of all files"
#


cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/sift/src/c/
cp imsmooth_acc.txt imsmooth.c
cp diffss_acc.txt diffss.c

cp imsmooth_apx.txt imsmooth.c

cd /home/polaris/behzad/behzad_local/apx_tool_chain/src/python_files/
python run_tool_chain.py

rm ../../generated_text/finalResult.png 
rm pickled_results_pareto
cp pickled_results_all_points all_of_s2
echo "done with the stage 2: apx of some files"



cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/sift/src/c/
cp imsmooth_acc.txt imsmooth.c
cp diffss_acc.txt diffss.c


cp diffss_apx.txt diffss.c

cd /home/polaris/behzad/behzad_local/apx_tool_chain/src/python_files/
python run_tool_chain.py
rm ../../generated_text/finalResult.png 
rm pickled_results_pareto
cp pickled_results_all_points all_of_s3
echo "done with the stage 3: apx of some files"

#returning all the files to approximate version (so we can get the accurate result)
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/sift/src/c/
cp imsmooth_apx.txt imsmooth.c
cp diffss_apx.txt diffss.c


cd /home/polaris/behzad/behzad_local/apx_tool_chain/src/python_files/
python combine_paretos.py
python compare_pareto_curves.py >> compare_results.txt
cp ../../generated_text/finalResult.png combine.png
echo "done with the stage 4:combining the paretos and comparing"

end=`date +%s`
runtime=$((end-start))
echo total running time of the script was: $runtime
