#!/bin/bash

start=`date +%s`
#removing all the previous files
# ---- starting stage 0
rm pareto_of_flattened
rm pareto_set_file.txt
rm ref.png
rm combine.png
rm pickled_results_pareto
rm pareto_of_combined
echo "done with the stage 0, removing all the files"

# ---- starting stage 1(running flattened)
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/localization/src/c/
cp eul2quat_apx.txt eul2quat.c
cp quatMul_apx.txt quatMul.c
cp fTimes_mod_apx.txt fTimes_mod.c
cp fMtimes_mod_apx.txt fMtimes_mod.c
cp script_localization_apx.txt script_localization.c

cd /home/polaris/behzad/behzad_local/apx_tool_chain_5/src/python_files/
python run_tool_chain.py
cp pickled_results_pareto pareto_of_flattened
cp pickled_results_all_points all_of_flattned
rm pareto_set_file.txt
cp ../../generated_text/finalResult.png ref.png
echo "done with the stage 1: flattening and apx of all files"


# ---- starting stage 2(apx some files)
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/localization/src/c/
cp fMtimes_mod_acc.txt fMtimes_mod.c
cp script_localization_acc.txt script_localization.c

cd /home/polaris/behzad/behzad_local/apx_tool_chain_5/src/python_files/
python run_tool_chain.py

rm ../../generated_text/finalResult.png 
rm pickled_results_pareto
cp pickled_results_all_points all_of_s2
echo "done with the stage 2: apx of some files"


# ---- starting stage 3(apx some files)
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/localization/src/c/
cp eul2quat_acc.txt eul2quat.c
cp quatMul_acc.txt quatMul.c
cp fTimes_mod_acc.txt fTimes_mod.c
cp fMtimes_mod_apx.txt fMtimes_mod.c
cp script_localization_apx.txt script_localization.c

cd /home/polaris/behzad/behzad_local/apx_tool_chain_5/src/python_files/
python run_tool_chain.py
rm ../../generated_text/finalResult.png 
rm pickled_results_pareto
cp pickled_results_all_points all_of_s3
echo "done with the stage 3: apx of some files"

# ---- starting stage 4(combine and compare)
#returning all the files to approximate version (so we can get the accurate result)
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/localization/src/c/
cp eul2quat_apx.txt eul2quat.c
cp quatMul_apx.txt quatMul.c
cp fTimes_mod_apx.txt fTimes_mod.c
cp fMtimes_mod_apx.txt fMtimes_mod.c
cp script_localization_apx.txt script_localization.c

cd /home/polaris/behzad/behzad_local/apx_tool_chain_5/src/python_files/
python combine_paretos.py
python compare_pareto_curves.py >> compare_results.txt
cp ../../generated_text/finalResult.png combine.png
echo "done with stage 4:combining the paretos and comparing"

end=`date +%s`
runtime=$((end-start))
echo total running time of the script was: $runtime
