#!/bin/bash

echo "======================"
echo "REMINDERS"
echo "======================"
echo "reminder: the command line argument order is the following"
echo "benchmark_name, root_folder,benchsuit_name"
echo 
echo 

benchmark=$1
root_folder=$2
bench_suit_name=$3
heuristic_intensity1=$4
heuristic_intensity2=$5

echo "======================"
echo "testing the $benchmark benchmark and dumping the results in $root_folder" 
echo "======================"
echo 
echo

start=`date +%s`


#
if [ "$benchmark" == "sift" ];then
echo
echo
echo "---------starting stage 0"
#removing all the previous files
rm nohup.out
rm pareto_of_heur_flattened
rm pareto_set_file.txt
rm pareto_of_all_of_flattened
rm ref.png
rm combine.png
rm pickled_results_pareto
rm pareto_of_combined
rm results.png
echo "done with the stage 0, removing all the files"


## ---- starting stage 1(apx all files, flattened version)
echo
echo
echo "---------starting stage 1"

python run_write_config.py $benchmark $root_folder $bench_suit_name $heuristic_intensity1
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/sift/src/c/
cp imsmooth_apx.txt imsmooth.c
cp diffss_apx.txt diffss.c

cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
python run_tool_chain.py
cp pickled_results_pareto pareto_of_heur_flattened
cp pickled_results_all_points all_of_flattned
cp pickled_results_pareto_of_all pareto_of_all_of_flattened

rm pareto_set_file.txt
cp ../../generated_text/finalResult.png ref.png
echo "done with the stage 1: flattening and apx of all files"


# ---- starting stage 2(apx some files)
echo
echo
echo "---------starting stage 2"
python run_write_config.py $benchmark $root_folder $bench_suit_name $heuristic_intensity2
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/sift/src/c/
cp imsmooth_acc.txt imsmooth.c
cp diffss_acc.txt diffss.c

cp imsmooth_apx.txt imsmooth.c

cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
python run_tool_chain.py

rm ../../generated_text/finalResult.png 
rm pickled_results_pareto
cp pickled_results_all_points all_of_s2
cp pickled_results_pareto_of_all pareto_of_all_of_s2
echo "done with the stage 2: apx of some files"


## ---- starting stage 3(apx some files)
echo
echo
echo "---------starting stage 3"
python run_write_config.py $benchmark $root_folder $bench_suit_name $heuristic_intensity2
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/sift/src/c/
cp imsmooth_acc.txt imsmooth.c
cp diffss_acc.txt diffss.c

cp diffss_apx.txt diffss.c

cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
python run_tool_chain.py
rm ../../generated_text/finalResult.png 
rm pickled_results_pareto
cp pickled_results_all_points all_of_s3
cp pickled_results_pareto_of_all pareto_of_all_of_s3
echo "done with the stage 3: apx of some files"


## ---- starting stage 4(permutation + comparison)
#returning all the files to approximate version (so we can get the accurate result)
echo
echo
echo "---------starting stage 4"
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/sift/src/c/
cp imsmooth_apx.txt imsmooth.c
cp diffss_apx.txt diffss.c

cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
python combine_paretos.py
python compare_pareto_curves.py >> compare_results.txt
cp ../../generated_text/finalResult.png combine.png
echo "done with the stage 4:combining the paretos and comparing"

elif [ $benchmark == "disparity" ];then
#removing all the previous files
echo
echo
echo "---------starting stage 0"
rm pareto_of_heur_flattened
rm pareto_set_file.txt
rm ref.png
rm combine.png
rm pickled_results_pareto
rm pareto_of_combined
echo "done with the stage 0, removing all the files"


## ---- starting stage 1(apx all files, flattened version)
echo
echo
echo "---------starting stage 1"
python run_write_config.py $benchmark $root_folder $bench_suit_name $heuristic_intensity1
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/disparity/src/c/
cp computeSAD_apx.txt computeSAD.c
cp finalSAD_apx.txt finalSAD.c
cp integralImage2D2D_apx.txt integralImage2D2D.c

cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
python run_tool_chain.py
cp pickled_results_pareto pareto_of_heur_flattened
cp pickled_results_all_points all_of_flattned
cp pickled_results_pareto_of_all pareto_of_all_of_flattened
rm pareto_set_file.txt
cp ../../generated_text/finalResult.png ref.png
echo "done with the stage 1: flattening and apx of all files"


## ---- starting stage 2(apx some files)
#echo
#echo
#echo "---------starting stage 2"
#python run_write_config.py $benchmark $root_folder $bench_suit_name $heuristic_intensity2
#cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/disparity/src/c/
#cp computeSAD_acc.txt computeSAD.c
#cp finalSAD_acc.txt finalSAD.c
#cp integralImage2D2D_acc.txt integralImage2D2D.c
#
#cp computeSAD_apx.txt computeSAD.c
#cp integralImage2D2D_apx.txt integralImage2D2D.c 
#
#cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
#python run_tool_chain.py
#
#rm ../../generated_text/finalResult.png 
#rm pickled_results_pareto
#cp pickled_results_all_points all_of_s2
#cp pickled_results_pareto_of_all pareto_of_all_of_s2
#echo "done with the stage 2: apx of some files"
#
#
### ---- starting stage 3(apx some files)
#echo
#echo
#echo "---------starting stage 3"
#python run_write_config.py $benchmark $root_folder $bench_suit_name $heuristic_intensity2
#cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/disparity/src/c/
#cp computeSAD_acc.txt computeSAD.c
#cp finalSAD_acc.txt finalSAD.c
#cp integralImage2D2D_acc.txt integralImage2D2D.c
#
#cp finalSAD_apx.txt finalSAD.c
#
#cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
#python run_tool_chain.py
#rm ../../generated_text/finalResult.png 
#rm pickled_results_pareto
#cp pickled_results_all_points all_of_s3
#cp pickled_results_pareto_of_all pareto_of_all_of_s3
#echo "done with the stage 3: apx of some files"
#
#
### ---- starting stage 4(combine and compare)
#echo
#echo
#echo "---------starting stage 4"
#cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/disparity/src/c/
##returning all the files to approximate version (so we can get the accurate result)
#cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/disparity/src/c/
#cp computeSAD_apx.txt computeSAD.c
#cp finalSAD_apx.txt finalSAD.c
#cp integralImage2D2D_apx.txt integralImage2D2D.c
#
#cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
#python combine_paretos.py
#python compare_pareto_curves.py >> compare_results.txt
#cp ../../generated_text/finalResult.png combine.png
#echo "done with stage 4:combining the paretos and comparing"
#
elif [ $benchmark == "localization" ];then
#removing all the previous files
# ---- starting stage 0
echo
echo
echo "---------starting stage 0"
rm pareto_of_heur_flattened
rm pareto_set_file.txt
rm ref.png
rm combine.png
rm pickled_results_pareto
rm pareto_of_combined
echo "done with the stage 0, removing all the files"

# ---- starting stage 1(running flattened)
echo
echo
echo "---------starting stage 1"
python run_write_config.py $benchmark $root_folder $bench_suit_name $heuristic_intensity1
cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/localization/src/c/
cp eul2quat_apx.txt eul2quat.c
cp quatMul_apx.txt quatMul.c
cp fTimes_mod_apx.txt fTimes_mod.c
cp fMtimes_mod_apx.txt fMtimes_mod.c
cp script_localization_apx.txt script_localization.c


cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
python run_tool_chain.py
cp pickled_results_pareto pareto_of_heur_flattened
cp pickled_results_all_points all_of_flattned
cp pickled_results_pareto_of_all pareto_of_all_of_flattened
rm pareto_set_file.txt
cp ../../generated_text/finalResult.png ref.png
echo "done with the stage 1: flattening and apx of all files"


## ---- starting stage 2(apx some files)
#echo
#echo
#echo "---------starting stage 2"
#python run_write_config.py $benchmark $root_folder $bench_suit_name $heuristic_intensity2
#cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/localization/src/c/
#cp fMtimes_mod_acc.txt fMtimes_mod.c
#cp script_localization_acc.txt script_localization.c
#
#cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
#python run_tool_chain.py
#
#rm ../../generated_text/finalResult.png 
#rm pickled_results_pareto
#cp pickled_results_all_points all_of_s2
#cp pickled_results_pareto_of_all pareto_of_all_of_s2
#echo "done with the stage 2: apx of some files"
#
#
## ---- starting stage 3(apx some files)
#echo
#echo
#echo "---------starting stage 3"
#python run_write_config.py $benchmark $root_folder $bench_suit_name $heuristic_intensity2
#cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/localization/src/c/
#cp eul2quat_acc.txt eul2quat.c
#cp quatMul_acc.txt quatMul.c
#cp fTimes_mod_acc.txt fTimes_mod.c
#cp fMtimes_mod_apx.txt fMtimes_mod.c
#cp script_localization_apx.txt script_localization.c
#
#cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
#python run_tool_chain.py
#rm ../../generated_text/finalResult.png 
#rm pickled_results_pareto
#cp pickled_results_all_points all_of_s3
#cp pickled_results_pareto_of_all pareto_of_all_of_s3
#echo "done with the stage 3: apx of some files"
#
## ---- starting stage 4(combine and compare)
##returning all the files to approximate version (so we can get the accurate result)
#echo
#echo
#echo "---------starting stage 4"
#cd /home/local/bulkhead/behzad/usr/local/sd-vbs/benchmarks/localization/src/c/
#cp eul2quat_apx.txt eul2quat.c
#cp quatMul_apx.txt quatMul.c
#cp fTimes_mod_apx.txt fTimes_mod.c
#cp fMtimes_mod_apx.txt fMtimes_mod.c
#cp script_localization_apx.txt script_localization.c
#
#cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
#python combine_paretos.py
#python compare_pareto_curves.py >> compare_results.txt
#cp ../../generated_text/finalResult.png combine.png
#echo "done with stage 4:combining the paretos and comparing"
elif [ "$benchmark" == "jpeg" ];then
echo
echo
echo "---------starting stage 0"
#removing all the previous files
rm pareto_of_heur_flattened
rm pareto_set_file.txt
rm ref.png
rm combine.png
rm pickled_results_pareto
rm pareto_of_combined
echo "done with the stage 0, removing all the files"


## ---- starting stage 1(apx all files, flattened version)
echo
echo
echo "---------starting stage 1"
python run_write_config.py $benchmark $root_folder $bench_suit_name $heuristic_intensity1
cd /home/polaris/behzad/behzad_local/"$root_folder"/src/CSrc/
cp dct_apx.txt dct.cpp
cp quant_apx.txt quant.cpp

cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
python run_tool_chain.py
cp pickled_results_pareto pareto_of_heur_flattened
cp pickled_results_all_points all_of_flattned
cp pickled_results_pareto_of_all pareto_of_all_of_flattened
rm pareto_set_file.txt
cp ../../generated_text/finalResult.png ref.png
echo "done with the stage 1: flattening and apx of all files"


## ---- starting stage 2(apx some files)
echo
echo
echo "---------starting stage 2"
python run_write_config.py $benchmark $root_folder $bench_suit_name $heuristic_intensity2
cd /home/polaris/behzad/behzad_local/"$root_folder"/src/CSrc/
cp dct_acc.txt dct.cpp
cp quant_acc.txt quant.cpp

cp dct_apx.txt dct.cpp

cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
python run_tool_chain.py

rm ../../generated_text/finalResult.png 
rm pickled_results_pareto
cp pickled_results_all_points all_of_s2
cp pickled_results_pareto_of_all pareto_of_all_of_s2
echo "done with the stage 2: apx of some files"


## ---- starting stage 3(apx some files)
echo
echo
echo "---------starting stage 3"
python run_write_config.py $benchmark $root_folder $bench_suit_name $heuristic_intensity2
cd /home/polaris/behzad/behzad_local/"$root_folder"/src/CSrc/
cp dct_acc.txt dct.cpp
cp quant_acc.txt quant.cpp

cp quant_apx.txt quant.cpp

cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
python run_tool_chain.py
rm ../../generated_text/finalResult.png 
rm pickled_results_pareto
cp pickled_results_all_points all_of_s3
cp pickled_results_pareto_of_all pareto_of_all_of_s3
echo "done with the stage 3: apx of some files"


## ---- starting stage 4(permutation + comparison)
#returning all the files to approximate version (so we can get the accurate result)
echo
echo
echo "---------starting stage 4"
cd /home/polaris/behzad/behzad_local/"$root_folder"/src/CSrc/
cp dct_apx.txt dct.cpp
cp quant_apx.txt quant.cpp

cd /home/polaris/behzad/behzad_local/"$root_folder"/src/python_files/
python combine_paretos.py
python compare_pareto_curves.py >> compare_results.txt
cp ../../generated_text/finalResult.png combine.png
echo "done with the stage 4:combining the paretos and comparing"
else
echo "this benchmark is not defined or accessable"
fi
python make_graphs.py ref
end=`date +%s`
runtime=$((end - start))
echo $runtime
runtime_in_min=$((runtime/60))
echo total running time of the script was: $runtime_in_min

